import type { Metadata } from "next";
import { getMarketNews, getCryptoQuotes } from "@/lib/alpha-vantage";
import { summarizeArticles } from "@/lib/gemini";
import { NewsCard } from "@/components/cards/news-card";
import { AdSlot } from "@/components/ads/ad-slot";
import { Card, CardContent } from "@/components/ui/card";
import { TrendingUp, TrendingDown } from "lucide-react";

export const revalidate = 900; // 15 min ISR

export const metadata: Metadata = {
  title: "Latest Crypto News & Updates | Dalal Streett",
  description: "Read the latest cryptocurrency, bitcoin, and blockchain news instantly.",
};

const WATCHLIST = ["BTC-USD", "ETH-USD", "BNB-USD", "SOL-USD", "XRP-USD", "ADA-USD", "AVAX-USD", "DOGE-USD"];

function ChangeChip({ change, pct }: { change: number; pct: number }) {
  const up = change >= 0;
  return (
    <span
      className={`flex items-center gap-0.5 text-sm font-semibold ${
        up ? "text-green-500" : "text-red-500"
      }`}
    >
      {up ? <TrendingUp className="h-3.5 w-3.5" /> : <TrendingDown className="h-3.5 w-3.5" />}
      {up ? "+" : ""}
      {change.toFixed(2)} ({up ? "+" : ""}
      {pct.toFixed(2)}%)
    </span>
  );
}

export default async function CryptoNewsPage() {
  // Parallel fetch — Crypto + news
  const [cryptos, rawNews] = await Promise.all([
    getCryptoQuotes(WATCHLIST).catch(() => []),
    getMarketNews("crypto,blockchain").catch(() => []),
  ]);

  // AI summarize top 10 articles server-side
  const summaries = await summarizeArticles(
    rawNews.map((a) => a.summary),
    10
  );

  // Zip articles + summaries
  const feed = rawNews.slice(0, 10).map((article, i) => ({
    article,
    summary: (summaries[i] && summaries[i].tldr !== "Summary unavailable.") 
      ? summaries[i] 
      : { tldr: article.summary, sentiment: (article.overall_sentiment_label as "Bullish" | "Bearish" | "Neutral") || "Neutral" },
  }));

  const btc = cryptos.find(c => c.symbol === "BTC-USD") || { symbol: "BTC-USD", price: 0, change: 0, changePercent: 0 };

  return (
    <>
      {/* ── HERO: Bitcoin ── */}
      <section className="py-6">
        <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
          Crypto — Live
        </p>
        <div className="mt-2 flex items-end gap-4">
          <div>
            <p className="text-xs text-muted-foreground">Bitcoin (BTC)</p>
            <p className="text-5xl font-black">
              ${btc.price.toLocaleString("en-US")}
            </p>
          </div>
          <ChangeChip change={btc.change} pct={btc.changePercent} />
        </div>
      </section>

      {/* ── ADSENSE SLOT 1 ── */}
      <AdSlot className="my-4" slotId="crypto-top" />

      {/* ── CRYPTO WATCHLIST ── */}
      <section className="mt-2">
        <h2 className="text-base font-bold mb-3">Top Cryptocurrencies</h2>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
          {cryptos.map((eq) => (
            <Card key={eq.symbol} className="hover:border-blue-500/40 transition-colors">
              <CardContent className="p-3">
                <p className="text-xs font-medium text-muted-foreground truncate">
                  {eq.symbol.replace('-USD', '')}
                </p>
                <p className="text-lg font-black mt-0.5">
                  ${eq.price.toLocaleString("en-US", { minimumFractionDigits: eq.price < 1 ? 4 : 2, maximumFractionDigits: eq.price < 1 ? 4 : 2 })}
                </p>
                <ChangeChip change={eq.change} pct={eq.changePercent} />
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* ── AI NEWS FEED ── */}
      <section className="mt-8">
        <h2 className="text-lg font-bold mb-4">
          Crypto News
          <span className="ml-2 text-xs font-normal text-muted-foreground">
            AI-summarized
          </span>
        </h2>

        <div className="space-y-3">
          {feed.map(({ article, summary }, idx) => (
            <div key={article.url}>
              {/* AdSense every 4th card — fixed height, zero CLS */}
              {idx > 0 && idx % 4 === 0 && (
                <AdSlot className="mb-3" slotId={`crypto-feed-${idx}`} />
              )}
              <NewsCard article={article} summary={summary} />
            </div>
          ))}
        </div>
      </section>

      {/* ── ADSENSE SLOT — end of feed ── */}
      <AdSlot className="mt-6" slotId="crypto-bottom" />

      {/* ── SEO COPY — bottom ── */}
      <section className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground mt-10">
        <h2>Cryptocurrency Market Updates & News</h2>
        <p>
          Live Bitcoin (BTC), Ethereum (ETH), and altcoin prices. Discover top blockchain and web3
          news updated every 15 minutes. Sentiment tags (Bullish/Bearish)
          generated by Google Gemini from article content.
        </p>
      </section>
    </>
  );
}
